# Copyright 2025 Pavel Sobolev
#
# This file is part of the Reachard project, located at
#
#     https://reachard.paveloom.dev
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: reachard
services:
  reachard:
    build: .
    depends_on:
      - db-clickhouse
      - db-postgresql
    restart: unless-stopped
    expose:
      - ${REACHARD_PORT:?error}
    environment:
      - REACHARD_HOST=${REACHARD_HOST?error}
      - REACHARD_PORT=${REACHARD_PORT:?error}
      - REACHARD_CLICKHOUSE_HOST=${REACHARD_CLICKHOUSE_HOST:?error}
      - REACHARD_CLICKHOUSE_PORT=${REACHARD_CLICKHOUSE_PORT?error}
      - REACHARD_CLICKHOUSE_DB=${REACHARD_CLICKHOUSE_DB:?error}
      - REACHARD_CLICKHOUSE_USER=${REACHARD_CLICKHOUSE_USER:?error}
      - REACHARD_CLICKHOUSE_PASSWORD=${REACHARD_CLICKHOUSE_PASSWORD:?error}
      - REACHARD_POSTGRESQL_HOST=${REACHARD_POSTGRESQL_HOST:?error}
      - REACHARD_POSTGRESQL_PORT=${REACHARD_POSTGRESQL_PORT?error}
      - REACHARD_POSTGRESQL_DB=${REACHARD_POSTGRESQL_DB:?error}
      - REACHARD_POSTGRESQL_USER=${REACHARD_POSTGRESQL_USER:?error}
      - REACHARD_POSTGRESQL_PASSWORD=${REACHARD_POSTGRESQL_PASSWORD:?error}
      - REACHARD_POSTGRESQL_SSLMODE=${REACHARD_POSTGRESQL_SSLMODE?error}
    develop:
      watch:
        - path: .
          action: rebuild
    networks:
      - db
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
  db-clickhouse:
    image: docker.io/clickhouse:25.8
    restart: unless-stopped
    environment:
      - CLICKHOUSE_DB=${REACHARD_CLICKHOUSE_DB:?error}
      - CLICKHOUSE_USER=${REACHARD_CLICKHOUSE_USER:?error}
      - CLICKHOUSE_PASSWORD=${REACHARD_CLICKHOUSE_PASSWORD:?error}
    networks:
      - db
    ports:
      - 127.0.0.1:8123:8123
    volumes:
      - db_clickhouse:/var/lib/clickhouse
  db-postgresql:
    image: docker.io/postgres:17
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${REACHARD_POSTGRESQL_DB:?error}
      - POSTGRES_USER=${REACHARD_POSTGRESQL_USER:?error}
      - POSTGRES_PASSWORD=${REACHARD_POSTGRESQL_PASSWORD:?error}
      - PGUSER=${REACHARD_POSTGRESQL_USER:?error}
    networks:
      - db
    volumes:
      - db_postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  db:
  traefik:
    external: true
volumes:
  db_clickhouse:
  db_postgresql:
