#!/usr/bin/env bash

reuse annotate \
    --copyright "Pavel Sobolev" \
    --copyright-prefix string \
    --year 2025 \
    --license "Apache-2.0" \
    --template apache \
    --skip-unrecognised \
    --merge-copyrights \
    --recursive .
